-- Seed data for videos table
-- Run this in Supabase SQL Editor after creating the tables

INSERT INTO videos (artist, artist_ja, song, song_ja, url1, url1_channel, url2, url2_channel, benefit_points) VALUES
('마사야', 'マサヤ', '이방인', '異邦人', 'https://www.youtube.com/watch?v=VcZHjL6jVRM', '트롯가왕', 'https://www.youtube.com/watch?v=IQ6h0sbChis', 'MBN Music', 0),
('마사야 , 조째즈', 'マサヤ , ジョジェズ', '실', '糸', 'https://www.youtube.com/watch?v=tthkgdaeEUI', '트롯가왕', 'https://www.youtube.com/watch?v=UezKGCe9T0E', 'MBN Music', 0),
('마사야', 'マサヤ', '보고싶다', '会いたい', 'https://www.youtube.com/watch?v=VP27khdDWhg', '트롯가왕', 'https://www.youtube.com/watch?v=fN61OsMW8Aw', 'MBN Music', 50000),
('마사야 , 에녹', 'マサヤ , エノク', '루비반지', 'ルビーの指環', 'https://www.youtube.com/watch?v=1shZfYzly88', '트롯가왕', 'https://www.youtube.com/watch?v=ZSSfZKxSy2s', 'MBN Music', 0),
('마사야', 'マサヤ', '오사카LOVER', '大阪LOVER', 'https://www.youtube.com/watch?v=1I2Nk26OW5A', '트롯가왕', 'https://www.youtube.com/watch?v=AZRza3WJ8uA', 'MBN Music', 0),
('마사야', 'マサヤ', 'TOMORROW', 'TOMORROW', 'https://www.youtube.com/watch?v=vx4WxsBCcmY', '트롯가왕', 'https://www.youtube.com/watch?v=QVpxx-gFiBs', 'MBN Music', 0),
('마사야', 'マサヤ', 'For You', 'For You', 'https://www.youtube.com/watch?v=75Un1G2deeQ', '트롯가왕', 'https://www.youtube.com/watch?v=A5BHnjKTSE4', 'MBN Music', 50000),
('마사야 , 신', 'マサヤ , シン', 'Rainy Blue', 'レイニーブルー', 'https://www.youtube.com/watch?v=ovapz7-acEg', '트롯가왕', 'https://www.youtube.com/watch?v=DEHWeC17lv0', 'MBN Music', 0),
('마사야 , 린', 'マサヤ , リン', 'My Destiny', 'My Destiny', 'https://www.youtube.com/watch?v=bpSU2KAn9RU', '트롯가왕', 'https://www.youtube.com/watch?v=rL2N0dL43R0', 'MBN Music', 0),
('마사야', 'マサヤ', 'TSUNAMI', 'TSUNAMI', 'https://www.youtube.com/watch?v=WBEpbg5wKdU', '트롯가왕', 'https://www.youtube.com/watch?v=jn2ShK0jtfs', 'MBN Music', 50000),
('마사야 , 황민호', 'マサヤ , ファンミノ', '아 옛날이여', 'あ、昔よ', 'https://www.youtube.com/watch?v=S9CBqIphkag', '트롯가왕', 'https://www.youtube.com/watch?v=vA9NbvAYmQE', 'MBN Music', 50000),
('박서진', 'パクソジン', '비와 당신', '雨とあなた', 'https://www.youtube.com/watch?v=bXyaW5KpWh0', '트롯가왕', 'https://www.youtube.com/watch?v=d4pWjMsd0go', 'MBN Music', 0),
('박서진', 'パクソジン', '청춘고백', '青春告白', 'https://www.youtube.com/watch?v=mwot7QrK42s', '트롯가왕', 'https://www.youtube.com/watch?v=As706sxdcvg', 'MBN Music', 0),
('박서진', 'パクソジン', '당신이야기', 'あなたの物語', 'https://www.youtube.com/watch?v=UvgPf94eOuk', '트롯가왕', 'https://www.youtube.com/watch?v=KcPXtpHhiuM', 'MBN Music', 0),
('박서진', 'パクソジン', '조사하면 다 나온다', '調べたら全部明かされる', 'https://www.youtube.com/watch?v=G-2B49JaiLA', '트롯가왕', 'https://www.youtube.com/watch?v=99dU0j3X5FE', 'MBN Music', 50000),
('박서진', 'パクソジン', '사랑 사랑 누가 말했나', '愛 愛 誰が言ったのか', 'https://www.youtube.com/watch?v=QkFMS4QLQBM', '트롯가왕', 'https://www.youtube.com/watch?v=Zx8UFnpJOTc', 'MBN Music', 50000),
('박서진', 'パクソジン', '울고 넘는 박달재', '泣いて越すバクダルジェ', 'https://www.youtube.com/watch?v=PfJtEJsGH8Q', '트롯가왕', 'https://www.youtube.com/watch?v=qA9SR7vZzkc', 'MBN Music', 0),
('박서진', 'パクソジン', '사랑가', '愛の歌', 'https://www.youtube.com/watch?v=ckcsbdU7Hbw', '트롯가왕', 'https://www.youtube.com/watch?v=6nhXrpbRj_g', 'MBN Music', 0),
('박서진', 'パクソジン', '카멜레온', 'カメレオン', 'https://www.youtube.com/watch?v=b-mIvNTtg_w', '트롯가왕', 'https://www.youtube.com/watch?v=N-CEeJJvml4', 'MBN Music', 0),
('박서진 , 민수현', 'パクソジン , ミンスヒョン', '쓰리랑', 'スリラン', 'https://www.youtube.com/watch?v=AnFqEs3j1pc', '트롯가왕', 'https://www.youtube.com/watch?v=t-OhrVr8GHs', 'MBN Music', 50000),
('진해성', 'ジンへソン', '목마른 사슴', 'のどの渇いたシカ', 'https://www.youtube.com/watch?v=E5iWkDkjnfs', '트롯가왕', 'https://www.youtube.com/watch?v=H23i3IyBoFo', 'MBN Music', 50000),
('진해성', 'ジンへソン', '야간열차', '夜行列車', 'https://www.youtube.com/watch?v=xSambFWEWLY', '트롯가왕', 'https://www.youtube.com/watch?v=dXVWv75PwVw', 'MBN Music', 0),
('진해성', 'ジンへソン', '아담과 이브처럼', 'アダムとエバのように', 'https://www.youtube.com/watch?v=VquTe4ntWXA', '트롯가왕', 'https://www.youtube.com/watch?v=Q1iHPQd0KyE', 'MBN Music', 0),
('진해성', 'ジンへソン', '내 사랑 경아', '私の愛 ギョンア', 'https://www.youtube.com/watch?v=IOcWv_jL4Gw', '트롯가왕', 'https://www.youtube.com/watch?v=XUkz3Mg-Bvg', 'MBN Music', 0),
('진해성', 'ジンへソン', '낙엽이 가는 길', '落ち葉が行く道', 'https://www.youtube.com/watch?v=9s3HgTr5F8k', '트롯가왕', 'https://www.youtube.com/watch?v=5aQ7lIQk858', 'MBN Music', 0),
('진해성', 'ジンへソン', '울긴 왜 울어', 'なんで泣く', 'https://www.youtube.com/watch?v=q6cud-wDtIk', '트롯가왕', 'https://www.youtube.com/watch?v=WgvEo69zbCw', 'MBN Music', 0),
('진해성 , 요요미', 'ジンへソン , ヨヨミ', '분위기 좋고', 'いい雰囲気', 'https://www.youtube.com/watch?v=izDWjOqJ6Jc', '트롯가왕', 'https://www.youtube.com/watch?v=2YnzLeGr2c4', 'MBN Music', 0),
('신승태', 'シンスンテ', '시절인연', '時節因縁', 'https://www.youtube.com/watch?v=91qwNklBqpY', '트롯가왕', 'https://www.youtube.com/watch?v=_e7vSRKwqJo', 'MBN Music', 50000),
('신승태', 'シンスンテ', '십분 내로', '十分内に', 'https://www.youtube.com/watch?v=D6NvejsYVko', '트롯가왕', 'https://www.youtube.com/watch?v=sjQnhR62UEc', 'MBN Music', 0),
('신승태', 'シンスンテ', '성은 김이요', '苗字はキムよ', 'https://www.youtube.com/watch?v=iMrO_IkUj8c', '트롯가왕', 'https://www.youtube.com/watch?v=TQZfLrwcI2A', 'MBN Music', 0),
('신승태', 'シンスンテ', '쓰러집니다', '倒れます', 'https://www.youtube.com/watch?v=czoI8E27s3Q', '트롯가왕', 'https://www.youtube.com/watch?v=OhIB0p1rTc0', 'MBN Music', 0),
('신승태', 'シンスンテ', '사랑의 밧줄', '愛のつな', 'https://www.youtube.com/watch?v=zUxAaXOh2SM', '트롯가왕', 'https://www.youtube.com/watch?v=ESaZfuzKeG8', 'MBN Music', 0),
('신승태 , 에녹 , 진해성', 'シンスンテ , エノク , ジンへソン', '다시 한번만', 'もう一度だけ', 'https://www.youtube.com/watch?v=_kpbMbwBmDY', '트롯가왕', 'https://www.youtube.com/watch?v=Ce9lJtnBQBA', 'MBN Music', 0),
('신승태 , 윤수현', 'シンスンテ , ユンスヒョン', '사랑의 포로', '愛の虜', 'https://www.youtube.com/watch?v=nN5mut5PQHs', '트롯가왕', 'https://www.youtube.com/watch?v=VzeBgv48DFo', 'MBN Music', 0),
('신승태 , 윤미라', 'シンスンテ , ユンミラ', '사랑의 이름표', '愛の名札', 'https://www.youtube.com/watch?v=S7C2uCJfFQY', '트롯가왕', 'https://www.youtube.com/watch?v=bhsI8lmJeZY', 'MBN Music', 0),
('다케나카 유다이', '竹中雄大', '사랑이라든가 연애라든가', '愛とか恋とか', 'https://www.youtube.com/watch?v=P2OAXJWbwwY', '트롯가왕', 'https://www.youtube.com/watch?v=C6qFfXyYIDk', 'MBN Music', 0),
('다케나카 유다이', '竹中雄大', '로빈슨', 'ロビンソン', 'https://www.youtube.com/watch?v=dAxPt1juAJA', '트롯가왕', 'https://www.youtube.com/watch?v=iBACf9tUgUA', 'MBN Music', 0),
('다케나카 유다이', '竹中雄大', 'Forever Love', 'Forever Love', 'https://www.youtube.com/watch?v=lURRwV27PKg', '트롯가왕', 'https://www.youtube.com/watch?v=VVd5EEpZuG4', 'MBN Music', 0),
('다케나카 유다이', '竹中雄大', '달맞이 꽃', 'ツキミソウ', 'https://www.youtube.com/watch?v=ZL9mUkh8EHc', '트롯가왕', 'https://www.youtube.com/watch?v=634W1YJz00I', 'MBN Music', 50000),
('다케나카 유다이', '竹中雄大', 'First Love', 'First Love', 'https://www.youtube.com/watch?v=xv8o67KARIo', '트롯가왕', 'https://www.youtube.com/watch?v=xfdZI_woY1A', 'MBN Music', 0),
('최수호', 'チェスホ', 'I Love you', 'I Love you', 'https://www.youtube.com/watch?v=l9Q8zXux4TE', '트롯가왕', 'https://www.youtube.com/watch?v=mrkh9NXhWBc', 'MBN Music', 0),
('최수호', 'チェスホ', '인연', '縁', 'https://www.youtube.com/watch?v=4LrGIySNlKs', '트롯가왕', 'https://www.youtube.com/watch?v=CKvFNG0ZoFM', 'MBN Music', 0),
('최수호', 'チェスホ', '모두 잠든 후에', 'みんなが眠った後', 'https://www.youtube.com/watch?v=IW_Ky4f7dvA', '트롯가왕', 'https://www.youtube.com/watch?v=SD-JAJcG1Sc', 'MBN Music', 0),
('최수호', 'チェスホ', '천년학', '千年鶴', 'https://www.youtube.com/watch?v=Vb-bsEgFP9Q', '트롯가왕', 'https://www.youtube.com/watch?v=h3uB36pHEKI', 'MBN Music', 0),
('쥬니', 'ジュニ', '눈물은 장식이 아니야', '飾りじゃないのよ涙は', 'https://www.youtube.com/watch?v=8Tylvkl8iDQ', '트롯가왕', 'https://www.youtube.com/watch?v=jqrnlULxTiI', 'MBN Music', 0),
('쥬니', 'ジュニ', '10 minutes', '10 minutes', 'https://www.youtube.com/watch?v=jD88bNgG8JI', '트롯가왕', 'https://www.youtube.com/watch?v=0hpgVwiq6e4', 'MBN Music', 0),
('최수호, 쥬니', 'チェスホ, ジュニ', '변덕스러운 로맨틱', '気まぐれロマンティック', 'https://www.youtube.com/watch?v=t0e96rr6gB0', '트롯가왕', 'https://www.youtube.com/watch?v=jiVL4MxSnwk', 'MBN Music', 0),
('쥬니 ,김다현', 'ジュニ ,キムダヒョン', '이제는', '今は', 'https://www.youtube.com/watch?v=oqpNeOvlcZg', '트롯가왕', 'https://www.youtube.com/watch?v=vj_HfdzBRIg', 'MBN Music', 50000),
('쥬니 , 성리', 'ジュニ , ソンリ', '바람 바람 바람', '風 風 風', 'https://www.youtube.com/watch?v=JR4RJYJXT_g', '트롯가왕', 'https://www.youtube.com/watch?v=jSBSa4ULGuY', 'MBN Music', 0),
('타쿠야 , 쥬니', 'タクヤ , ジュニ', '코이', '恋', 'https://www.youtube.com/watch?v=Vqi_t_yxdVc', '트롯가왕', 'https://www.youtube.com/watch?v=wv0Hi35371E', 'MBN Music', 0),
('타쿠야 , 박서진', 'タクヤ , パクソジン', '겁쟁이', '臆病者', 'https://www.youtube.com/watch?v=f1tozEGeO8c', '트롯가왕', 'https://www.youtube.com/watch?v=i8CGpSBxutU', 'MBN Music', 50000),
('타쿠야', 'タクヤ', 'Blue Bird', 'ブルーバード', 'https://www.youtube.com/watch?v=GSmqIny-DMU', '트롯가왕', 'https://www.youtube.com/watch?v=jwzTxlatOXk', 'MBN Music', 50000),
('타쿠야 , 신', 'タクヤ , シン', '연분홍빛 춤출 무렵', '桜色舞うころ', 'https://www.youtube.com/watch?v=xmYdRZS6jxI', '트롯가왕', 'https://www.youtube.com/watch?v=s7f4b8lj7kg', 'MBN Music', 0),
('타쿠야 , 진해성', 'タクヤ , ジンへソン', '오직 하나뿐인 그대', 'たった一人だけのあなた', 'https://www.youtube.com/watch?v=liSMhINBPRw', '트롯가왕', 'https://www.youtube.com/watch?v=xgHEd7nTDBk', 'MBN Music', 0),
('타쿠야', 'タクヤ', '히로인', 'ヒロイン', 'https://www.youtube.com/watch?v=jIcpVco4rp4', '트롯가왕', 'https://www.youtube.com/watch?v=A5UJZSlVZVQ', 'MBN Music', 0),
('에녹', 'エノク', '흔적', '跡', 'https://www.youtube.com/watch?v=iOJeBj0Qaq4', '트롯가왕', 'https://www.youtube.com/watch?v=PJ7cbDs1kfk', 'MBN Music', 0),
('에녹', 'エノク', '묻어버린 아픔', '埋めてしまった痛み', 'https://www.youtube.com/watch?v=hCXjlIo4ed0', '트롯가왕', 'https://www.youtube.com/watch?v=eks10uWHow0', 'MBN Music', 0),
('에녹', 'エノク', '잡초', '雑草', 'https://www.youtube.com/watch?v=1dBI8MIMHQE', '트롯가왕', 'https://www.youtube.com/watch?v=-AMBW8YF1Bo', 'MBN Music', 0),
('에녹', 'エノク', '오! 사라', 'お！サラ', 'https://www.youtube.com/watch?v=dPm4WwJcGE8', '트롯가왕', 'https://www.youtube.com/watch?v=7riX1V1QqkA', 'MBN Music', 0),
('에녹', 'エノク', '사랑은 마술처럼', '愛は魔術のように', 'https://www.youtube.com/watch?v=-PFSyJm2WqQ', '트롯가왕', 'https://www.youtube.com/watch?v=71mxn6JMhOI', 'MBN Music', 0),
('에녹, 김다현', 'エノク, キムダヒョン', '그대 먼 곳에', 'あなた 遠いところへ', 'https://www.youtube.com/watch?v=15DyNC_CKq0', '트롯가왕', 'https://www.youtube.com/watch?v=WDBRO2Vvoik', 'MBN Music', 0),
('에녹, 마리아', 'エノク, マリア', '나를 살게 하는 사랑', '私を生かす愛', 'https://www.youtube.com/watch?v=HnkhnCD0y6M', '트롯가왕', 'https://www.youtube.com/watch?v=EZz05LHvi44', 'MBN Music', 50000),
('에녹', 'エノク', '떠날 수 없는 당신', '離れられないあなた', 'https://www.youtube.com/watch?v=wWy8D6ny8jA', '트롯가왕', 'https://www.youtube.com/watch?v=BG7JfuddbII', 'MBN Music', 0),
('에녹, 신영숙', 'エノク, シンヨンスク', '아버지', 'お父さん', 'https://www.youtube.com/watch?v=pL5JOv_A9Fs', '트롯가왕', 'https://www.youtube.com/watch?v=s_1AHgIeg38', 'MBN Music', 0),
('슈, 신', 'シュウ, シン', '그대에게', 'あなたに', 'https://www.youtube.com/watch?v=QfRY87K7Fw0', '트롯가왕', 'https://www.youtube.com/watch?v=xAoCPfAwhhE', 'MBN Music', 0),
('슈', 'シュウ', '눈물의 바다에 안기고 싶어', '涙の海で抱かれたい～SEA OF LOVE', 'https://www.youtube.com/watch?v=QPfrtgzVFmY', '트롯가왕', 'https://www.youtube.com/watch?v=TejZnV0mjss', 'MBN Music', 0),
('슈', 'シュウ', '사랑스러워', '可愛らしい', 'https://www.youtube.com/watch?v=g803bZVkdEA', '트롯가왕', 'https://www.youtube.com/watch?v=1X5d6apr79I', 'MBN Music', 50000),
('신', 'シン', '텅 빈 마음', '空っぽの心', 'https://www.youtube.com/watch?v=gd6d0FxC4tk', '트롯가왕', 'https://www.youtube.com/watch?v=YGfB8THMqGE', 'MBN Music', 0),
('신', 'シン', '내 사랑 내 곁에', '私の愛、私のそばに', 'https://www.youtube.com/watch?v=bPCVkLUUZPY', '트롯가왕', 'https://www.youtube.com/watch?v=2jYLvAQLmYk', 'MBN Music', 0),
('신, 진해성', 'シン, ジンへソン', '찬 바람이 불면', '冷たい風が吹けば', 'https://www.youtube.com/watch?v=xG1ge6Fy7vo', '트롯가왕', 'https://www.youtube.com/watch?v=U7LxJPvBqhc', 'MBN Music', 0),
('슈, 신, 쥬니, 타쿠야', 'シュウ, シン, ジュニ, タクヤ', '자기야', 'ダーリン', 'https://www.youtube.com/watch?v=-RfnLGHuIzU', '트롯가왕', 'https://www.youtube.com/watch?v=Qrsl1zy1-0c', 'MBN Music', 0),
('김준수', 'キムジュンス', '안동역에서', 'アンドン駅で', 'https://www.youtube.com/watch?v=oDQI-ahK0yA', '트롯가왕', 'https://www.youtube.com/watch?v=091vf1LNTpE', 'MBN Music', 0),
('김준수', 'キムジュンス', '담배가게 아가씨', 'タバコ屋のお嬢さん', 'https://www.youtube.com/watch?v=SFiJDZg0g50', '트롯가왕', 'https://www.youtube.com/watch?v=rIP0mKHa2u4', 'MBN Music', 50000),
('김준수, 민은경', 'キムジュンス, ミンウンギョン', '사랑, 결코 시들지 않는', '愛、決して枯れない', 'https://www.youtube.com/watch?v=rH1eqCGh__E', '트롯가왕', 'https://www.youtube.com/watch?v=ooYhL3_VSUo', 'MBN Music', 50000),
('강문경', 'カンムンギョン', '행운', '幸運', 'https://www.youtube.com/watch?v=88apQbvbgcY', '트롯가왕', 'https://www.youtube.com/watch?v=uKt90X9LNGU', 'MBN Music', 0),
('타쿠야', 'タクヤ', 'LOVE SONG', 'LOVE SONG', 'https://www.youtube.com/watch?v=p5txfjAolUM', '트롯가왕', '', '', 0);
